# Generated by Django 6.1.1 on 2026-09-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketevent',
            old_name='careated_at',
            new_name='created_at',
        ),
    ]
