# Generated by Django 6.1.1 on 2026-10-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_rename_careated_at_ticketevent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='category_counts',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='priority_counts',
            field=models.JSONField(default=dict),
        ),
    ]
