from rest_framework import serializers
from django.contrib.auth.models import User

from triage.services import ticket
from triage.services.notifications import send_ticket_event

from .models import Customer, Ticket, TicketEvent, DailyReport


class CustomerSerializer(serializers.ModelSerializer):
    class Meta:
        model = Customer
        fields = "__all__"

class TicketEventSerializer(serializers.ModelSerializer):
    class Meta:
        model = TicketEvent
        fields = "__all__"


class TicketSerializer(serializers.ModelSerializer):
    events = TicketEventSerializer(many=True, read_only=True)

    # Customer information for public ticket creation
    customer_email = serializers.EmailField(
        write_only=True,
        required=True
    )
    customer_name = serializers.CharField(
        write_only=True,
        required=True
    )

    # These are generated by the backend
    ticket_id = serializers.CharField(read_only=True)
    created_at = serializers.DateTimeField(read_only=True)

    class Meta:
        model = Ticket
        fields = [
            "id",
            "ticket_id",
            "customer",
            "customer_email",
            "customer_name",
            "subject",
            "description",
            "category",
            "status",
            "priority",
            "channel",
            "assigned_agent",
            "created_at",
            "resolved_at",
            "sla_breached",
            "events",
        ]

        read_only_fields = [
            "id",
            "ticket_id",
            "customer",
            "priority",
            "assigned_agent",
            "created_at",
            "resolved_at",
            "sla_breached",
            "events",
        ]

    def create(self, validated_data):
        from django.utils import timezone
        from uuid import uuid4
        from .services.priority import get_priority_with_repeat_customer
        from .tasks import send_ticket_acknowledgement

        customer_email = validated_data.pop("customer_email")
        customer_name = validated_data.pop("customer_name")

        # Find existing customer by email
        customer = Customer.objects.filter(
            email__iexact=customer_email
        ).first()

        # Create customer if not found
        if not customer:
            customer = Customer.objects.create(
                customer_id=f"CUST-{uuid4().hex[:8].upper()}",
                customer_name=customer_name,
                email=customer_email,
            )

        # Generate ticket ID
        validated_data["ticket_id"] = f"TKT-{uuid4().hex[:8].upper()}"

        # Generate creation time
        validated_data["created_at"] = timezone.now()

        # Attach customer
        validated_data["customer"] = customer

        ticket = Ticket.objects.create(**validated_data)

        # Calculate priority
        ticket.priority = get_priority_with_repeat_customer(ticket)
        ticket.save(update_fields=["priority"])

        # Create audit event
        TicketEvent.objects.create(
            ticket=ticket,
            event_type="CREATED",
            description="Ticket created.",
        )

        # Send real-time notification
        send_ticket_event(
            ticket,
            "ticket.created",
            {
                "status": ticket.status,
                "priority": ticket.priority,
                "category": ticket.category,
            },
        )

        # Send acknowledgement email
        if ticket.customer.email:
            send_ticket_acknowledgement.delay(
                ticket.ticket_id,
                ticket.customer.email,
            )

        return ticket

    def update(self, instance, validated_data):
        if instance.status == "Closed":
            raise serializers.ValidationError(
                {"detail": "Closed tickets cannot be modified."}
            )

        from .services.ticket import update_ticket_status

        new_status = validated_data.get("status")

        if new_status and new_status != instance.status:
            update_ticket_status(instance, new_status)
            validated_data.pop("status")

        for attr, value in validated_data.items():
            setattr(instance, attr, value)

        instance.save()

        return instance




class DailyReportSerializer(serializers.ModelSerializer):
    class Meta:
        model = DailyReport
        fields = "__all__"


class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ["id", "username", "email"]